server:
  port: 9092  # Spring boot Server port

spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /h2-console  # 콘솔의 경로
      settings:
        trace: true

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:axon-rom;AUTO_SERVER=TRUE  #접속 URL
    username: axon-rom  # 사용자 이름 (로그인 시 사용)
    password: 1234  # 사용자 암호 (로그인 시 사용)
  jpa:
    show-sql: true


#  jpa:
#    database-platform=org:
#      hibernate:
#        dialect: H2Dialect
#  jdbc:h2:tcp://localhost:9092/default
